In [1]:
import pandas as pd
import numpy as np

Create the dataset from the tabular colummn

In [2]:
data={
    "Brightness":[40,50,60,10,70,60,25],
    "Saturation":[20,50,90,25,70,10,80],
    "Class":["Red","Blue","Blue","Red","Blue","Red","Blue"]
}
df=pd.DataFrame(data)
df

   Brightness  Saturation Class
0          40          20   Red
1          50          50  Blue
2          60          90  Blue
3          10          25   Red
4          70          70  Blue
5          60          10   Red
6          25          80  Blue

# Define the new entry

Defines the new data point whose Euclidean distance from every existing record will be calculated.

In [3]:
new_point=np.array([50,40])
print("New Entry")
print("Brightness =",new_point[0])
print("Saturation =",new_point[1])

New Entry
Brightness = 50
Saturation = 40

Calculate Euclidean distance

i had a lot of difficulty learning this concept

In [4]:
dist=[]
for i in range(len(df)):
    point=np.array([df.loc[i,"Brightness"],df.loc[i,"Saturation"]])
    d=np.sqrt(np.sum((point-new_point)**2))
    dist.append(d)
df["Euclidean Distance"]=dist
df

   Brightness  Saturation Class  Euclidean Distance
0          40          20   Red           22.360680
1          50          50  Blue           10.000000
2          60          90  Blue           50.990195
3          10          25   Red           42.720019
4          70          70  Blue           36.055513
5          60          10   Red           31.622777
6          25          80  Blue           47.169906

Sort by nearest neighbour

In [5]:
df=df.sort_values("Euclidean Distance")
df

   Brightness  Saturation Class  Euclidean Distance
1          50          50  Blue           10.000000
0          40          20   Red           22.360680
5          60          10   Red           31.622777
4          70          70  Blue           36.055513
3          10          25   Red           42.720019
6          25          80  Blue           47.169906
2          60          90  Blue           50.990195